Repository Solvro/web-planer, pull requests merged in 2025-01, with the labels that each got.

#123 feat: connect rating with backend
  frontend/src/app/plans/edit/[id]/page.client.tsx
  frontend/src/components/class-block.tsx
  frontend/src/components/class-schedule.tsx
  frontend/src/lib/types.ts
  frontend/src/lib/utils/update-local-plan.ts
  frontend/src/types/index.ts
Labels: enhancement

#139 fix(backend): lecturers scraper
  backend/.env.development
  backend/app/scrap-lecturers/scrap_lecturers.ts
  backend/commands/lecturers.ts
Labels: bug

#140 feat(backend): add Polwro logging to scraper
  backend/.env.development
  backend/app/scrap-lecturers/polwro_login.ts
  backend/app/scrap-lecturers/scrap_lecturers.ts
Labels: bug, enhancement
