Repository Solvro/web-planer, pull requests merged in 2025-08, with the labels that each got.

#258 feat: horizontal plan
  frontend/src/app/plans/edit/[id]/_components/app-sidebar.tsx
  frontend/src/app/plans/edit/[id]/page.client.tsx
  frontend/src/atoms/plan-orientation.ts
  frontend/src/components/class-block.tsx
  frontend/src/components/class-schedule.tsx
  frontend/src/components/hour.tsx
  frontend/src/components/plan-orientation-button.tsx
  frontend/src/hooks/use-plan-orientation.tsx
  frontend/tailwind.config.ts
Labels: size/L

#260 feat: schedule algorithm
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/plans/edit/[id]/_components/app-sidebar.tsx
  frontend/src/app/plans/edit/[id]/page.client.tsx
  frontend/src/components/algo-dialog.tsx
  frontend/src/components/magicui/particles.tsx
  frontend/src/components/plan-orientation-button.tsx
  frontend/src/components/ui/signout-button.tsx
  frontend/src/hooks/use-mobile.tsx
  frontend/src/lib/utils/schedule-algorithm.ts
  frontend/src/lib/utils/server-to-local-plan.ts
Labels: size/XL

#271 feat: registrations count in plan item
  frontend/src/app/plans/page.client.tsx
  frontend/src/components/plan-item.tsx
Labels: size/M

#276 fix(frontend): courses view
  frontend/src/components/groups-accordion.tsx
Labels: size/S

#278 feat(frontend): normalization start and end class hours
  frontend/src/components/class-block.tsx
  frontend/src/components/class-schedule.tsx
Labels: size/M
